global:
  env: default

default:
  replicas: 2

  service_name: gateway-service

  api_prefix: "/gateway/"

  ext_hostname: example.com
  
  tls_secret_name: example.com-tls

  memory_limit: 1024Mi
# memory limit 
  env_variables:
    CONTAINER_LOGGER_LOGROTATE_MAX_STDOUT_SIZE: "10MB"
    CONTAINER_LOGGER_LOGROTATE_MAX_STDERR_SIZE: "10MB"
    CONTAINER_LOGGER_LOGROTATE_STDOUT_OPTIONS: "rotate 100"
    CONTAINER_LOGGER_LOGROTATE_STDERR_OPTIONS: "rotate 100"
    DEBUG: "false"
    NAMING_SERVER: "http://naming-service:8761/eureka"
    SHUTDOWN_TIMEOUT: "30"
    PROFILE: "prod"
    TOKEN_ENDPOINT: "http://authentication-service:8086/oauth/token"
    PUBLIC_KEY_ENDPOINT: "http://authentication-service:8086/oauth/token_key"

    
